app = "Fly"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  FLOOD_WINDOW_SEC = "8"
  FLOOD_MAX_MSG = "6"
  REPEAT_MAX = "3"
  LINK_SPAM_ENABLED = "1"
  DB_PATH = "/data/bot.db"

[[mounts]]
  source = "botdata"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
